replicaCount: 2

image:
  repository: ghcr.io/zekihan/hornkeeper
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

controller:
  longhornNamespace: longhorn
  defaultBackupTarget: default
  defaultReplicas: 3
  resyncInterval: 1m
  leaderElection: true
  logLevel: info

rbac:
  create: true
serviceAccount:
  create: true
  name: ""
  annotations: {}

metrics:
  enabled: false

podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 25000
  runAsGroup: 25000
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
