{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hornkeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hornkeeper.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hornkeeper.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
{{- end }}
