apiVersion: v1
kind: Service
metadata:
  name: hornkeeper
  namespace: hornkeeper
spec:
  selector:
    app.kubernetes.io/name: hornkeeper
  ports:
    - name: health
      port: 8081
      targetPort: health
