apiVersion: v1
kind: Service
metadata:
  name: hornkeeper
  namespace: hornkeeper
spec:
  selector:
    app.kubernetes.io/name: hornkeeper
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
